### ISSUE TITLE
ART!!!!!!

### ISSUE THREAD

**Issue by th3tard1sparadox** [sornas/ultimate-fishbee#9]
- [x] Frisbees (@th3tard1sparadox)
  - [x] Base
  - [x] Overlay patterns (3 animation frames)
- [x] Fish 1 (3 animation frames) (@th3tard1sparadox)
- [x] Fish 2 (3 animation frames) (@vollells)
- [x] Fish 3 (3 animation frames) (@sornas)
- [x] Curtains (tiled) (@th3tard1sparadox)
- [x] Waves (tiled) (@sornas)
- [x] Boat rail (tiled) (@th3tard1sparadox)
- [x] Font (~~A-Z~~ & 0-9 & $ & +) (@sornas)
- [x] Logo (@th3tard1sparadox)
- [x] Shop button (add text from font?) (@th3tard1sparadox)
- [x] Start button (@th3tard1sparadox)
- [x] Gold particles (@th3tard1sparadox)
- [x] Water particles (@sornas)
- [ ] Air particles?
- [x] Shopkeep (@th3tard1sparadox)
- [x] background (@th3tard1sparadox)

**Comment by th3tard1sparadox** [comment]
![fishies](https://user-images.githubusercontent.com/43249770/117505640-aa249480-af84-11eb-86c4-867facb97209.png)

**Comment by sornas** [comment]
![fishy](https://user-images.githubusercontent.com/4735435/117550652-c2a6b480-b041-11eb-8b1d-f09b2cae311b.gif)
